In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import glob

## Importar todos csv

In [68]:
df = pd.concat(map(pd.read_csv, glob.glob('../data/raw/*.csv')))

In [69]:
len(df)

24842185

In [72]:
df.head()

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_EstacionArribo,Fecha_Arribo,Hora_Arribo
0,M,26.0,5180930,568,31/12/2024,23:57:02,572,01/01/2025,00:00:03
1,F,54.0,3653953,283,31/12/2024,23:51:40,596,01/01/2025,00:00:41
2,M,38.0,7511322,034,31/12/2024,23:48:36,064,01/01/2025,00:00:59
3,M,41.0,3804572,258,31/12/2024,23:54:11,023,01/01/2025,00:01:08
4,M,35.0,3848405,043,31/12/2024,23:35:28,126,01/01/2025,00:01:17

In [73]:
df.describe()

       Edad_Usuario          Bici
count  2.484083e+07  2.484218e+07
mean   3.423000e+01  5.465387e+06
std    9.809131e+00  2.023869e+06
min    1.600000e+01  2.000461e+06
25%    2.700000e+01  3.733581e+06
50%    3.200000e+01  5.472956e+06
75%    3.900000e+01  7.213606e+06
max    1.430000e+02  8.999708e+06

In [74]:
# Cambiar el nombre de las columnas a minúsculas
df.columns = df.columns.str.lower()
df

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacionarribo,fecha_arribo,hora_arribo
0,M,26.0,5180930,568,31/12/2024,23:57:02,572,01/01/2025,00:00:03
1,F,54.0,3653953,283,31/12/2024,23:51:40,596,01/01/2025,00:00:41
2,M,38.0,7511322,034,31/12/2024,23:48:36,064,01/01/2025,00:00:59
3,M,41.0,3804572,258,31/12/2024,23:54:11,023,01/01/2025,00:01:08
4,M,35.0,3848405,043,31/12/2024,23:35:28,126,01/01/2025,00:01:17
...,...,...,...,...,...,...,...,...,...
1653368,M,24.0,7926967,136,31/03/2026,23:40:23,294,31/03/2026,23:59:20
1653369,M,32.0,4106449,001,31/03/2026,23:40:14,549,31/03/2026,23:59:25
1653370,M,43.0,5261508,231,31/03/2026,23:41:27,034,31/03/2026,23:59:31
1653371,M,40.0,3127792,158-159,31/03/2026,23:52:01,129,31/03/2026,23:59:37
1653372,M,29.0,2794444,641,31/03/2026,23:41:13,668,31/03/2026,23:59:50

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24842185 entries, 0 to 1653372
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   genero_usuario         object
 1   edad_usuario           float64
 2   bici                   int64
 3   ciclo_estacion_retiro  object
 4   fecha_retiro           object
 5   hora_retiro            object
 6   ciclo_estacionarribo   object
 7   fecha_arribo           object
 8   hora_arribo            object
dtypes: float64(1), int64(1), object(7)
memory usage: 1.9+ GB

### Formato correcto

In [78]:
cols = ["bici","ciclo_estacion_retiro","ciclo_estacionarribo"]

df[cols] = df[cols].apply(pd.to_numeric, errors="coerce").astype("Int64")

In [79]:
df['hora_arribo'] = pd.to_datetime(df['hora_arribo'], format='%H:%M:%S')

In [80]:
df['hora_retiro'] = pd.to_datetime(df['hora_retiro'], format='%H:%M:%S')

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24842185 entries, 0 to 1653372
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   genero_usuario         object
 1   edad_usuario           float64
 2   bici                   Int64
 3   ciclo_estacion_retiro  Int64
 4   fecha_retiro           object
 5   hora_retiro            datetime64[ns]
 6   ciclo_estacionarribo   Int64
 7   fecha_arribo           object
 8   hora_arribo            datetime64[ns]
dtypes: Int64(3), datetime64[ns](2), float64(1), object(3)
memory usage: 1.9+ GB

In [85]:
df.head()

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacionarribo,fecha_arribo,hora_arribo
0,M,26.0,5180930,568,31/12/2024,1900-01-01 23:57:02,572,01/01/2025,1900-01-01 00:00:03
1,F,54.0,3653953,283,31/12/2024,1900-01-01 23:51:40,596,01/01/2025,1900-01-01 00:00:41
2,M,38.0,7511322,34,31/12/2024,1900-01-01 23:48:36,64,01/01/2025,1900-01-01 00:00:59
3,M,41.0,3804572,258,31/12/2024,1900-01-01 23:54:11,23,01/01/2025,1900-01-01 00:01:08
4,M,35.0,3848405,43,31/12/2024,1900-01-01 23:35:28,126,01/01/2025,1900-01-01 00:01:17

In [ ]:
# porcentaje de valores nulos por columna
df.tail()

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacionarribo,fecha_arribo,hora_arribo
1653368,M,24.0,7926967,136,31/03/2026,1900-01-01 23:40:23,294,31/03/2026,1900-01-01 23:59:20
1653369,M,32.0,4106449,1,31/03/2026,1900-01-01 23:40:14,549,31/03/2026,1900-01-01 23:59:25
1653370,M,43.0,5261508,231,31/03/2026,1900-01-01 23:41:27,34,31/03/2026,1900-01-01 23:59:31
1653371,M,40.0,3127792,<NA>,31/03/2026,1900-01-01 23:52:01,129,31/03/2026,1900-01-01 23:59:37
1653372,M,29.0,2794444,641,31/03/2026,1900-01-01 23:41:13,668,31/03/2026,1900-01-01 23:59:50

In [ ]:
#genero_usuario tiene 0, pero edad_usuario tiene 1, entonces se eliminará esa fila
df.isnull().sum()

genero_usuario                28
edad_usuario                1352
bici                           0
ciclo_estacion_retiro     931493
fecha_retiro                   0
hora_retiro                    0
ciclo_estacionarribo     1056864
fecha_arribo                   0
hora_arribo                    0
dtype: int64

In [ ]:
# porcentaje de valores nulos por columna
print(df.isnull().mean() * 100)

genero_usuario           0.000113
edad_usuario             0.005442
bici                     0.000000
ciclo_estacion_retiro    3.749642
fecha_retiro             0.000000
hora_retiro              0.000000
ciclo_estacionarribo     4.254312
fecha_arribo             0.000000
hora_arribo              0.000000
dtype: float64

In [ ]:
# Se eliminarán las filas con valores nulos en las columnas críticas para el análisis
columnas_criticas = ['ciclo_estacionarribo','ciclo_estacion_retiro','edad_usuario','genero_usuario']
df.dropna(subset=columnas_criticas, inplace=True)

In [91]:
df.isnull().sum()

genero_usuario           0
edad_usuario             0
bici                     0
ciclo_estacion_retiro    0
fecha_retiro             0
hora_retiro              0
ciclo_estacionarribo     0
fecha_arribo             0
hora_arribo              0
dtype: int64

In [97]:
df['fecha'] =  df['hora_arribo'] - df['hora_retiro']

df['fecha']

0         -1 days +00:03:01
1         -1 days +00:09:01
2         -1 days +00:12:23
3         -1 days +00:06:57
4         -1 days +00:25:49
                 ...
1653367     0 days 00:10:19
1653368     0 days 00:18:57
1653369     0 days 00:19:11
1653370     0 days 00:18:04
1653372     0 days 00:18:37
Name: fecha, Length: 22907263, dtype: timedelta64[ns]

In [98]:
# Convierte cualquier diferencia negativa en positiva
df['fecha'] = df['fecha'].abs()

df['fecha']

0         0 days 23:56:59
1         0 days 23:50:59
2         0 days 23:47:37
3         0 days 23:53:03
4         0 days 23:34:11
                ...
1653367   0 days 00:10:19
1653368   0 days 00:18:57
1653369   0 days 00:19:11
1653370   0 days 00:18:04
1653372   0 days 00:18:37
Name: fecha, Length: 22907263, dtype: timedelta64[ns]

In [100]:
# ver outliers
df['fecha'].describe()

count                     22907263
mean     0 days 00:18:34.875057050
std      0 days 01:11:19.823862652
min                0 days 00:00:10
25%                0 days 00:07:02
50%                0 days 00:11:46
75%                0 days 00:19:52
max                0 days 23:59:03
Name: fecha, dtype: object

In [120]:
cantidad =(df['fecha'] > pd.Timedelta(minutes=30)).sum()

In [121]:
cantidad

np.int64(2377419)

In [122]:
df.head()

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacionarribo,fecha_arribo,hora_arribo,fecha
0,M,26.0,5180930,568,31/12/2024,1900-01-01 23:57:02,572,01/01/2025,1900-01-01 00:00:03,0 days 23:56:59
1,F,54.0,3653953,283,31/12/2024,1900-01-01 23:51:40,596,01/01/2025,1900-01-01 00:00:41,0 days 23:50:59
2,M,38.0,7511322,34,31/12/2024,1900-01-01 23:48:36,64,01/01/2025,1900-01-01 00:00:59,0 days 23:47:37
3,M,41.0,3804572,258,31/12/2024,1900-01-01 23:54:11,23,01/01/2025,1900-01-01 00:01:08,0 days 23:53:03
4,M,35.0,3848405,43,31/12/2024,1900-01-01 23:35:28,126,01/01/2025,1900-01-01 00:01:17,0 days 23:34:11