In [ ]:
import pandas as pd
import glob

In [ ]:
# Cargar los archivos CSV en un DataFrame
df = pd.concat(map(pd.read_csv, glob.glob("../../data/raw/*.csv")))
df.columns

Index(['Genero_Usuario', 'Edad_Usuario', 'Bici', 'Ciclo_Estacion_Retiro',
       'Fecha_Retiro', 'Hora_Retiro', 'Ciclo_EstacionArribo', 'Fecha Arribo',
       'Hora_Arribo', 'Fecha_Arribo'],
      dtype='object')

In [3]:
len(df)

57609229

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57609229 entries, 0 to 1528609
Data columns (total 10 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Genero_Usuario         object
 1   Edad_Usuario           float64
 2   Bici                   int64
 3   Ciclo_Estacion_Retiro  object
 4   Fecha_Retiro           object
 5   Hora_Retiro            object
 6   Ciclo_EstacionArribo   object
 7   Fecha Arribo           object
 8   Hora_Arribo            object
 9   Fecha_Arribo           object
dtypes: float64(1), int64(1), object(8)
memory usage: 4.7+ GB

In [5]:
df

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_EstacionArribo,Fecha Arribo,Hora_Arribo,Fecha_Arribo
0,M,45.0,3297082,150,31/12/2022,23:58:00,040,01/01/2023,00:06:24,NaN
1,F,27.0,8922254,214,31/12/2022,23:36:34,025,01/01/2023,00:07:08,NaN
2,M,34.0,2320075,214,31/12/2022,23:36:33,025,01/01/2023,00:07:12,NaN
3,M,58.0,2096493,137,31/12/2022,23:57:19,036,01/01/2023,00:07:48,NaN
4,M,23.0,6294433,260,31/12/2022,23:57:42,043,01/01/2023,00:09:33,NaN
...,...,...,...,...,...,...,...,...,...,...
1528605,M,28.0,3033859,047,28/02/2026,23:26:35,133,NaN,23:59:18,28/02/2026
1528606,M,56.0,3235702,589,28/02/2026,23:28:37,692,NaN,23:59:53,28/02/2026
1528607,M,23.0,2858025,010,28/02/2026,23:47:56,561,NaN,23:59:53,28/02/2026
1528608,M,20.0,3780988,536,28/02/2026,23:48:00,536,NaN,23:59:55,28/02/2026
1528609,M,32.0,4767521,361,28/02/2026,23:54:25,359,NaN,23:59:57,28/02/2026

In [6]:
# Cambiar el nombre de las columnas a minúsculas
df.columns = df.columns.str.lower()
df.columns

Index(['genero_usuario', 'edad_usuario', 'bici', 'ciclo_estacion_retiro',
       'fecha_retiro', 'hora_retiro', 'ciclo_estacionarribo', 'fecha arribo',
       'hora_arribo', 'fecha_arribo'],
      dtype='object')

In [7]:
# Reemplazar espacios y caracteres especiales por guiones bajos
df.columns = df.columns.str.replace(r'\W+', '_', regex=True)
df.columns

Index(['genero_usuario', 'edad_usuario', 'bici', 'ciclo_estacion_retiro',
       'fecha_retiro', 'hora_retiro', 'ciclo_estacionarribo', 'fecha_arribo',
       'hora_arribo', 'fecha_arribo'],
      dtype='object')

In [8]:
df.head()

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacionarribo,fecha_arribo,hora_arribo,fecha_arribo
0,M,45.0,3297082,150,31/12/2022,23:58:00,040,01/01/2023,00:06:24,NaN
1,F,27.0,8922254,214,31/12/2022,23:36:34,025,01/01/2023,00:07:08,NaN
2,M,34.0,2320075,214,31/12/2022,23:36:33,025,01/01/2023,00:07:12,NaN
3,M,58.0,2096493,137,31/12/2022,23:57:19,036,01/01/2023,00:07:48,NaN
4,M,23.0,6294433,260,31/12/2022,23:57:42,043,01/01/2023,00:09:33,NaN

In [9]:
df.iloc[:0]
df.iloc[:1]

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacionarribo,fecha_arribo,hora_arribo,fecha_arribo
0,M,45.0,3297082,150,31/12/2022,23:58:00,040,01/01/2023,00:06:24,NaN

In [11]:
df.loc[:, "fecha_arribo"]

        fecha_arribo fecha_arribo
0         01/01/2023          NaN
1         01/01/2023          NaN
2         01/01/2023          NaN
3         01/01/2023          NaN
4         01/01/2023          NaN
...              ...          ...
1528605          NaN   28/02/2026
1528606          NaN   28/02/2026
1528607          NaN   28/02/2026
1528608          NaN   28/02/2026
1528609          NaN   28/02/2026

[57609229 rows x 2 columns]

In [12]:
df.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
        True])

In [13]:
#indice de las columnas
[i for i, col in enumerate(df.columns) if col == "fecha_arribo"]

[7, 9]

In [14]:
# Renombrar columnas duplicadas
cols = pd.Series(df.columns)
for dup in cols[cols.duplicated()].unique():
    cols[cols[cols == dup].index] = [
        f"{dup}_{i}" if i != 0 else dup
        for i in range(sum(cols == dup))
    ]

df.columns = cols

In [16]:
# combinar las columnas "fecha_arribo" y "fecha_arribo_1" en una nueva columna "fecha_arribo_final"
df["fecha_arribo_final"] = df["fecha_arribo"].combine_first(df["fecha_arribo_1"])

In [17]:
# eliminar las columnas originales "fecha_arribo" y "fecha_arribo_1"
df.drop(columns=["fecha_arribo", "fecha_arribo_1"], inplace=True)

In [18]:
df.columns

Index(['genero_usuario', 'edad_usuario', 'bici', 'ciclo_estacion_retiro',
       'fecha_retiro', 'hora_retiro', 'ciclo_estacionarribo', 'hora_arribo',
       'fecha_arribo_final'],
      dtype='object')

In [21]:
df["edad_usuario"] = df["edad_usuario"].astype("Int64")

In [24]:
#Cambiar el tipo de dato de las columnas "bici", "ciclo_estacion_retiro" y "ciclo_estacionarribo" a enteros, manejando los errores con "coerce" para convertir los valores no convertibles en NaN, y luego convertir la serie resultante a tipo "Int64" para permitir valores enteros con NaN.
cols = ["bici","ciclo_estacion_retiro","ciclo_estacionarribo"]


df[cols] = df[cols].apply(pd.to_numeric, errors="coerce").astype("Int64")

In [29]:
df["fecha_arribo_final"] = pd.to_datetime(
    df["fecha_arribo_final"],
    dayfirst=True,
    errors="coerce"
)

In [23]:
df.head()

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacionarribo,hora_arribo,fecha_arribo_final
0,M,45,3297082,150,31/12/2022,23:58:00,040,00:06:24,01/01/2023
1,F,27,8922254,214,31/12/2022,23:36:34,025,00:07:08,01/01/2023
2,M,34,2320075,214,31/12/2022,23:36:33,025,00:07:12,01/01/2023
3,M,58,2096493,137,31/12/2022,23:57:19,036,00:07:48,01/01/2023
4,M,23,6294433,260,31/12/2022,23:57:42,043,00:09:33,01/01/2023

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57609229 entries, 0 to 1528609
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   genero_usuario         object
 1   edad_usuario           Int64
 2   bici                   Int64
 3   ciclo_estacion_retiro  Int64
 4   fecha_retiro           object
 5   hora_retiro            object
 6   ciclo_estacionarribo   Int64
 7   hora_arribo            object
 8   fecha_arribo_final     datetime64[ns]
dtypes: Int64(4), datetime64[ns](1), object(4)
memory usage: 4.5+ GB

In [31]:
#Crear Nuevo csv Para analisis EDA

df.to_csv("../../data/processed/eco_bici_cdmx.csv", index=False)